### ISSUE TITLE
矢量图

### ISSUE THREAD

**Issue by Lete114** [zhheo/Sticker-Heo#9]
洪哥有矢量图版本吗？
![image](https://user-images.githubusercontent.com/48512251/148394408-509b4e17-5b56-4de4-a361-045eddb7802e.png)

**Comment by zhheo** [comment]
虽然是通过矢量软件绘制，但是考虑到版权争议，不对外提供

**Comment by Lete114** [comment]
> 虽然是通过矢量软件绘制，但是考虑到版权争议，不对外提供

好吧，明白
